workspace = '/home/lucas/projects/github'
shell = [
    '/usr/local/bin/zsh',
    '-cu',
]

# default_after_workon = 'echo default after workon'
# default_after_clone = 'echo default after clone'
# github_token = 'githubtokensecret'
# [gitlab]
# token = 'token'
# host = 'localhost'
