description = "Git database"

# Directories to index.
dirs = [ "~/projects/github" ]

# skip = "Dirs"
ignore_symlinks = true
ignore_hidden = false
gitignore = true

# Colored output (optional '#' or '0x' prefix)
# color = "FF5813"
