((function_statement (function_signature (arguments)) @cursor) @endable @indent (#endwise! "end"))
((do_statement "do" @cursor) @endable @indent (#endwise! "end"))
((generic_for_statement body: (for_body "do" @cursor)) @endable @indent (#endwise! "end"))
((while_statement (while_body "do" @cursor)) @endable @indent (#endwise! "end"))
((if_statement "then" @cursor) @endable @indent (#endwise! "end"))

((ERROR ("function" . (_)? . (function_signature (arguments)) @cursor) @indent) (#endwise! "end"))
((ERROR ("do" @cursor @indent)) (#endwise! "end"))
((ERROR ("for" @indent . "do" @cursor)) (#endwise! "end"))
((ERROR ("while" @indent . "do" @cursor)) (#endwise! "end"))
((ERROR ("if" @indent . (_) . "then" @cursor)) (#endwise! "end"))
