#!/bin/sh

# init
tmux new-session -s scripts -d -n shell -c "$HOME/mybin"
tmux new-window -t scripts:2 -n funcs -c "$ZDOTDIR/functions"

# window shell
cd "$HOME/mybin"
tmux split-window -t scripts:1.1 -h
# tmux split-window -t scripts:1.2 -v

cd "$ZDOTDIR/functions"
tmux split-window -t scripts:2.1 -h

# reset window
tmux select-pane -t scripts:1.1
tmux select-pane -t scripts:2.1
tmux select-window -t scripts:1
