---@meta

---@alias CodeAction
---| "''"
---| "'cursor'"
---| "'line'"
---| "'currline'"
---| "'refactor'" base kind for refactoring actions
---| "'quickfix'" base kind for quickfix actions
---| "'refactor.extract'" base kind for refactoring extraction actions
---| "'refactor.inline'" base kind for refactoring inline actions
---| "'refactor.rewrite'" base kind for refactoring rewrite actions
---| "'source'" base kind for source actions
---| "'source.organizeImports'" base kind for an organize imports source action
---| "'source.fixAll'" base kind for auto-fix source actions

---@alias SymbolKind
---|  '"Array"'
---|  '"Boolean"'
---|  '"Class"'
---|  '"Constant"'
---|  '"Constructor"'
---|  '"Enum"'
---|  '"EnumMember"'
---|  '"Event"'
---|  '"Field"'
---|  '"File"'
---|  '"Function"'
---|  '"Interface"'
---|  '"Key"'
---|  '"Method"'
---|  '"Module"'
---|  '"Namespace"'
---|  '"Null"'
---|  '"Number"'
---|  '"Object"'
---|  '"Operator"'
---|  '"Package"'
---|  '"Property"'
---|  '"String"'
---|  '"Struct"'
---|  '"TypeParameter"'
---|  '"Variable"'

---@class Outline
---@field filter_kind SymbolKind[]
---@field fzf boolean
---@field bufnr number?
