---@meta
---@description Types for my custom API for Neovim color/syntax functions

---@alias Color.S_t  string  a color's hex representation as a string
---@alias Color.N_t  integer a color's hex representation as a number
---@alias Highlight.Group string  the highlight group name

---@class Color.RGB_t
---@field r integer red channel
---@field g integer green channel
---@field b integer blue channel

---@class Highlight.Attr
---@field from string origin highlight group
---@field alter float number to alter by
---@field attr "'foreground'"|"'fg'"|"'background'"|"'bg'"|"'special'"|"'sp'"

---@alias Color_t string|integer|"'NONE'"|Highlight.Attr|fun():string|Highlight.Attr

---@class Highlight_t
---@field default       boolean         don't override existing definition
---@field fg            Color_t         foreground attribute
---@field bg            Color_t         background attribute
---@field sp            Color_t         special attribute
---@field foreground    Color_t         foreground attribute
---@field background    Color_t         background attribute
---@field special       Color_t         special attribute
---@field blend         number          0 to 100
---@field bold          boolean         bolden text for the highlight attribute
---@field standout      boolean         possibly similar to `bold`?
---@field underline     boolean         normal underline attribute
---@field undercurl     boolean         curled underline attribute
---@field underdouble   boolean         double underline attribute
---@field underdotted   boolean         dotted underline attribute
---@field underdashed   boolean         dashed underline attribute
---@field strikethrough boolean         strike through highlight attribute
---@field italic        boolean         italicize text for the highlight attribute
---@field reverse       boolean         reverse highlight attribute
---@field nocombine     boolean         override attributes instead of combining them
---@field link          boolean|string  link highlight group to another
---@field ctermfg       string          sets foreground of cterm color
---@field ctermbg       string          sets background of cterm color
---@field cterm         Cterm.Kind      cterm attribute map
---@field inherit       string          (extra) inherit color information from an already defined highlight group
---@field build         boolean         (extra) keep color attributes to build upon. (equiv: `val = {inherit='val'}`)
---@field gui           string          (extra) accept old GUI strings
---@field cond          string          (extra) conditional colorscheme name
---@field guifg         string          @deprecated foreground
---@field guibg         string          @deprecated background
---@field guisp         string          @deprecated special

---@alias Highlight.Kind
---| '"default"'       don't override existing definition
---| '"fg"'            foreground attribute
---| '"bg"'            background attribute
---| '"sp"'            special attribute
---| '"foreground"'    foreground attribute
---| '"background"'    background attribute
---| '"special"'       special attribute
---| '"bold"'          bolden text for the highlight attribute
---| '"standout"'      possibly similar to `bold`?
---| '"underline"'     normal underline attribute
---| '"undercurl"'     curled underline attribute
---| '"underdouble"'   double underline attribute
---| '"underdotted"'   dotted underline attribute
---| '"underdashed"'   dashed underline attribute
---| '"strikethrough"' strike through highlight attribute
---| '"italic"'        italicize text for the highlight attribute
---| '"reverse"'       reverse highlight attribute
---| '"nocombine"'     override attributes instead of combining them
---| '"link"'          link highlight group to another
---| '"ctermfg"'       cterm foreground
---| '"ctermbg"'       cterm background
---| '"inherit"'       [CUSTOM]: inherit color information from an already defined highlight group
---| '"build"'         [CUSTOM]: keep color attributes to build upon. (equiv: `val = {inherit='val'}`)
---| '"gui"'           [CUSTOM]: accept old GUI strings
---| '"cond"'          [CUSTOM]: conditional colorscheme name
---| '"guifg"'         @deprecated foreground
---| '"guibg"'         @deprecated background
---| '"guisp"'         @deprecated special

---@class Highlight.Map
---@field [string] Highlight_t

---@alias Cterm.Kind
---| '"bold"'
---| '"underline"'
---| '"undercurl"'     curly underline
---| '"underdouble"'   double underline
---| '"underdotted"'   dotted underline
---| '"underdashed"'   dashed underline
---| '"strikethrough"'
---| '"reverse"'
---| '"inverse"'       same as reverse
---| '"italic"'
---| '"standout"'
---| '"altfont"'
---| '"nocombine"'     override attributes instead of combining them
---| '"none"'          no attributes used (used to reset it)

---@class Highlight.Gui.Attr
---@field bold boolean
---@field italic boolean
---@field underline boolean
---@field undercurl boolean
---@field underdouble boolean
---@field underdotted boolean
---@field underdashed boolean
---@field strikethrough boolean
