---@meta

---@class ListBufOpts
---@field loaded boolean buffer valid and loaded
---@field valid boolean buffer is valid
---@field listed boolean buffer that is buflisted
---@field modified boolean buffer that is modified
---@field empty boolean buffer that is empty
---@field no_hidden boolean buffer that is not hidden
---@field tabpage integer buffer that is in a given tabpage
---@field winnr integer|integer[] buffer that is in a given window number(s)
---@field winid integer|integer[] buffer that is in a given window ID(s)
---@field buftype string|string[] buffer that is of a given type(s)
---@field bufname string buffer whose filename matches a given Lua pattern
---@field bufpath string buffer whose full-path matches a given Lua pattern
---@field options Dict<any> buffer that matches a given map of options
---@field vars Dict<any> buffer that matches a given map of variables
