---@meta

---@class PackerPlugin
---@field name? string Name of plugin
---@field after? string|string[] Specifies plugins to load before this plugin.
---@field requires? string|string[]|string[][] Specifies plugin dependencies
---@field wants? string|string[] Load the plugins if they're not already
---@field rocks? string|string[] Specifies Luarocks dependencies for the plugin
---@field as? string Specifies an alias under which to install the plugin
---@field config? string|fun() Specifies code to run after this plugin is loaded.
---@field conf? string [CUSTOM]: Specifies code to run after this plugin is loaded.
---@field setup? string|fun() Specifies code to run before this plugin is loaded.
---@field run? string|string[]|fun(v: PackerPlugin)|fun(v: PackerPlugin)[] Post-update/install hook
---@field installer? fun() Specifies custom installer
---@field updater? fun() Specifies custom updater
---@field lock? boolean Skip updating this plugin in updates/syncs. Still cleans.
---@field frozen? boolean Unsure: possibly same as lock
---@field opt? boolean Manually marks a plugin as optional.
---@field cond? string|fun(): boolean|string[] Specifies a conditional test to load this plugin
---@field cmd? string|string[] Specifies commands which load this plugin.  Can be an autocmd pattern.
---@field ft? string|string[] Specifies filetypes which load this plugin.
---@field keys? string|string[]|string[][] Specifies maps which load this plugin
---@field event? string|string[] Specifies autocommand events which load this plugin.
---@field fn? string|string[] Specifies functions which load this plugin.
---@field module? string|string[] Specifies Lua module names for require
---@field module_pattern? string|string[] Specifies Lua pattern of Lua module names for require
---@field disable? boolean Mark a plugin as inactive
---@field disablep? boolean [CUSTOM]: Mark a plugin as inactive if it is disabled in `usr.control`
---@field rtp? string Specifies a subdirectory of the plugin to add to runtimepath.
---@field patch? boolean|string [CUSTOM]: Specifies a patch to apply to the plugin
---@field branch? string Specifies a git branch to use
---@field commit? string Specifies a git commit to use
---@field rev? string Specifies a git commit to use
---@field tag? string Specifies a git tag to use. Supports '*' for "latest tag"
---@field bufread? boolean Manually specifying if a plugin needs BufRead after being loaded
---@field simple_load? boolean Unsure: only load the plugin as if no args were passed
---@field url? string URL to the Git repository
---@field install_path? string Directory where plugin is to be installed
---@field manual_opt? boolean Unsure
---@field only_config? boolean Unsure
---@field short_name? string Name of plugin minus the user
---@field desc? string [CUSTOM]: Just a way of writing a description of the plugin
