edition                      = "2021"
newline_style                = "Unix"
tab_spaces                   = 4
hard_tabs                    = false
unstable_features            = true
comment_width                = 80
wrap_comments                = true
normalize_comments           = true
normalize_doc_attributes     = true # #[doc] -> //!
error_on_line_overflow       = false # change to fix errors
error_on_unformatted         = false
format_code_in_doc_comments  = true
format_macro_bodies          = true
format_macro_matchers        = true # $a: ident -> $a:ident
format_strings               = true
imports_granularity          = "Crate"
imports_layout               = "HorizontalVertical"
group_imports                = "StdExternalCrate" # create 3 groups
reorder_imports              = true
reorder_modules              = true
reorder_impl_items           = true
match_arm_blocks             = true
match_block_trailing_comma   = true
trailing_semicolon           = true # continue, break, return
trailing_comma               = "Vertical"
overflow_delimited_expr      = true
use_field_init_shorthand     = true  # F { x: x } -> F { x }
use_try_shorthand            = true  # try!() -> ()?
empty_item_single_line       = true  # fn foo() {}
fn_single_line               = false # not fn foo() { println!() }
where_single_line            = false
chain_width                  = 60
max_width                    = 106
doc_comment_code_block_width = 106
enum_descrim_align_threshold = 20
struct_field_align_threshold = 20
struct_lit_width             = 30
struct_variant_width         = 60
combine_control_expr         = true  # if expr within fn call
condense_wildcard_suffixes   = true  # (_, _) -> ( .. )
merge_derives                = true
spaces_around_ranges         = false # 1 .. 5 -> 1..5
type_punctuation_density     = "Wide" # S: Display+Debug=Foo -> spaces

color                        = "Auto"
hex_literal_case             = "Upper" # "Preserve"
# remove_nested_parens         = true

array_width = 60
attr_fn_like_width = 70
binop_separator = "Front"
blank_lines_lower_bound = 0
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
control_brace_style = "AlwaysSameLine"
fn_args_layout = "Tall"
fn_call_width = 60
force_explicit_abi = true
force_multiline_blocks = false
hide_parse_errors = false
imports_indent = "Block"
indent_style = "Block"
inline_attribute_width = 0
match_arm_leading_pipes = "Never"
short_array_element_width_threshold = 10
single_line_if_else_max_width = 50
space_after_colon = true
space_before_colon = false
struct_lit_single_line = true

# report_fixme = "Always"
# report_todo  = "Always"
