zstyle :plugin:fast-syntax-highlighting theme "mod-default"
typeset -g FAST_THEME_NAME="mod-default"
: ${FAST_HIGHLIGHT_STYLES[mod-defaultdefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultunknown-token]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultreserved-word]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultalias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultsuffix-alias]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultbuiltin]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultfunction]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultcommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultprecommand]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultcommandseparator]:=none}
: ${FAST_HIGHLIGHT_STYLES[mod-defaulthashed-command]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultpath]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultpath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultglobbing]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultglobbing-ext]:=fg=13}
: ${FAST_HIGHLIGHT_STYLES[mod-defaulthistory-expansion]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultsingle-hyphen-option]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultdouble-hyphen-option]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultsingle-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultdouble-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultdollar-quoted-argument]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultback-or-dollar-double-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultback-dollar-quoted-argument]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultredirection]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultcomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultvariable]:=fg=14}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultmathvar]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultmathnum]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultmatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultassign-array-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultfor-loop-variable]:=fg=magenta,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultfor-loop-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultfor-loop-operator]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultfor-loop-separator]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultexec-descriptor]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaulthere-string-tri]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaulthere-string-text]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaulthere-string-var]:=fg=cyan}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultsecondary]:=mod-backup}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultcase-input]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultcase-parentheses]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultcase-condition]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultcorrect-subtle]:=fg=12}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultincorrect-subtle]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultsubtle-separator]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultsubtle-bg]:=fg=9}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultpath-to-dir]:=fg=magenta,underline}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultpaired-bracket]:=bg=red}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultbracket-level-1]:=fg=green,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultbracket-level-2]:=fg=yellow,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultbracket-level-3]:=fg=cyan,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultglobal-alias]:=fg=red,bold}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultsubcommand]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultsingle-sq-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultdouble-sq-bracket]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultdouble-paren]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultoptarg-string]:=fg=yellow}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultoptarg-number]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[mod-defaultrecursive-base]:=none}
