zstyle :plugin:fast-syntax-highlighting theme "kimbox"
typeset -g FAST_THEME_NAME="kimbox"
: ${FAST_HIGHLIGHT_STYLES[kimboxdefault]:=none}
: ${FAST_HIGHLIGHT_STYLES[kimboxunknown-token]:=fg=#dc3958,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxreserved-word]:=fg=#98676A}
: ${FAST_HIGHLIGHT_STYLES[kimboxalias]:=fg=#4c96a8}
: ${FAST_HIGHLIGHT_STYLES[kimboxsuffix-alias]:=fg=#7EB2B1}
: ${FAST_HIGHLIGHT_STYLES[kimboxbuiltin]:=fg=#dc3958}
: ${FAST_HIGHLIGHT_STYLES[kimboxfunction]:=fg=#924f79}
: ${FAST_HIGHLIGHT_STYLES[kimboxcommand]:=fg=#819c3b}
: ${FAST_HIGHLIGHT_STYLES[kimboxprecommand]:=fg=#A06469,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxcommandseparator]:=fg=#FF5813}
: ${FAST_HIGHLIGHT_STYLES[kimboxhashed-command]:=fg=#819c3b}
: ${FAST_HIGHLIGHT_STYLES[kimboxpath]:=fg=magenta}
: ${FAST_HIGHLIGHT_STYLES[kimboxpath_pathseparator]:=}
: ${FAST_HIGHLIGHT_STYLES[kimboxglobbing]:=fg=blue,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxglobbing-ext]:=fg=#924f79}
: ${FAST_HIGHLIGHT_STYLES[kimboxhistory-expansion]:=fg=#a43a57,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxsingle-hyphen-option]:=fg=#088649}
: ${FAST_HIGHLIGHT_STYLES[kimboxdouble-hyphen-option]:=fg=#088649}
: ${FAST_HIGHLIGHT_STYLES[kimboxback-quoted-argument]:=none}
: ${FAST_HIGHLIGHT_STYLES[kimboxsingle-quoted-argument]:=fg=#f79a32}
: ${FAST_HIGHLIGHT_STYLES[kimboxdouble-quoted-argument]:=fg=#f79a32}
: ${FAST_HIGHLIGHT_STYLES[kimboxdollar-quoted-argument]:=fg=#689d69}
: ${FAST_HIGHLIGHT_STYLES[kimboxback-or-dollar-double-quoted-argument]:=fg=#088649}
: ${FAST_HIGHLIGHT_STYLES[kimboxback-dollar-quoted-argument]:=fg=#088649}
: ${FAST_HIGHLIGHT_STYLES[kimboxassign]:=none}
: ${FAST_HIGHLIGHT_STYLES[kimboxredirection]:=fg=#4c96a8,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxcomment]:=fg=black,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxvariable]:=fg=#4c96a8}
: ${FAST_HIGHLIGHT_STYLES[kimboxmathvar]:=fg=#7e5053,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxmathnum]:=fg=#819C3B,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxmatherr]:=fg=red}
: ${FAST_HIGHLIGHT_STYLES[kimboxassign-array-bracket]:=fg=#7EB2B1}
: ${FAST_HIGHLIGHT_STYLES[kimboxfor-loop-variable]:=fg=#fe8019,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxfor-loop-number]:=fg=#819C3B,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxfor-loop-operator]:=fg=#7fbbb3}
: ${FAST_HIGHLIGHT_STYLES[kimboxfor-loop-separator]:=fg=#dc3958,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxexec-descriptor]:=fg=#fe8019,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxhere-string-tri]:=fg=#924f79}
: ${FAST_HIGHLIGHT_STYLES[kimboxhere-string-text]:=fg=#f79a32}
: ${FAST_HIGHLIGHT_STYLES[kimboxhere-string-var]:=fg=#689d69}
: ${FAST_HIGHLIGHT_STYLES[kimboxsecondary]:=mod-backup}
: ${FAST_HIGHLIGHT_STYLES[kimboxcase-input]:=fg=#fe8019,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxcase-parentheses]:=fg=#FF5813}
: ${FAST_HIGHLIGHT_STYLES[kimboxcase-condition]:=fg=#a3b95a,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxcorrect-subtle]:=fg=#b16185}
: ${FAST_HIGHLIGHT_STYLES[kimboxincorrect-subtle]:=fg=#f14a68}
: ${FAST_HIGHLIGHT_STYLES[kimboxsubtle-separator]:=fg=green}
: ${FAST_HIGHLIGHT_STYLES[kimboxsubtle-bg]:=fg=9}
: ${FAST_HIGHLIGHT_STYLES[kimboxpath-to-dir]:=fg=magenta,underline}
: ${FAST_HIGHLIGHT_STYLES[kimboxpaired-bracket]:=bg=#dc3958}
: ${FAST_HIGHLIGHT_STYLES[kimboxbracket-level-1]:=fg=#a3b95a,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxbracket-level-2]:=fg=#FF9500,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxbracket-level-3]:=fg=#7EB2B1,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxglobal-alias]:=fg=#dc3958,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxsubcommand]:=fg=#f79a32}
: ${FAST_HIGHLIGHT_STYLES[kimboxsingle-sq-bracket]:=fg=#819c3b}
: ${FAST_HIGHLIGHT_STYLES[kimboxdouble-sq-bracket]:=fg=#FF5813}
: ${FAST_HIGHLIGHT_STYLES[kimboxdouble-paren]:=fg=#FF5813}
: ${FAST_HIGHLIGHT_STYLES[kimboxoptarg-string]:=fg=#f79a32}
: ${FAST_HIGHLIGHT_STYLES[kimboxoptarg-number]:=fg=#819C3B,bold}
: ${FAST_HIGHLIGHT_STYLES[kimboxrecursive-base]:=none}
