Completion:
  AllScopes: Yes

InlayHints:
  Enabled: Yes
  Designators: Yes
  ParameterNames: Yes
  DeducedTypes: Yes

Hover:
  ShowAKA: Yes

Diagnostics:
  UnusedIncludes: Strict
  # Suppress: [-Wunused-result, -Wunused, -Wunused-variable]
  # https://clang.llvm.org/extra/clang-tidy/checks/list.html
  ClangTidy:
    # modernize-* misc-*
    Add: bugprone-*
  # Remove: modernize-use-trailing-return-type

Index:
  StandardLibrary: Yes

# -g = Add debugging
# -fverbose-asm = If compiling with '-S' examine assemble output
# -finstrument-functions = Adds code to call user supplied profiling functions
# --coverage = gcov
# -fsanitize={address,thread,undefined}

CompileFlags:
  Add: [
      -Wall,               # all warnings
      -Wextra,             # extra warnings
      -Wpedantic,
      -Wfloat-equal,       # testing floats for equality
      -Wundef,             # unitialized identifier evaluated in an #if
      -Wshadow,            # variable shadows another
      -Wpointer-arith,     # anything dpends upon size of func or void
      -Wcast-align,        # pointer is cast such that required alignment of target is increased
      -Wstrict-prototypes, # func declared/defined without specifying variables
      -Wstrict-overflow=5,
      -Wwrite-strings,     # string constants 'const'
      -Waggregate-return,  # funcs that return structs/unions are defined
      -Wcast-qual,         # pointer is cast to remove a type qualifier from target type
      -Wswitch-default,    # switch statement does not have default
      -Wswitch-enum,       # switch statement has index of enum type last a case for an enumeration
      -Wconversion,        # implicit conversions that may alter value
      -Wunreachable-code,  # self explanatory
      -Wformat=2,
      -Winit-self,
      -fsanitize=address,
      # -fsanitize=thread,
      -fsanitize=undefined,
      -save-temps,           # leave behind results of preprocess and assembly

      # Disable
      -Wno-unused-result,
      -Wno-unused,
      -Wno-unused-variable
    ]
  Remove: []
  # Remove: -W*
---

# Flags for .c files
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [
    -xc,
    -std=gnu2x,            # c standard  c2x
  ]
Compiler: clang
---
# Flags for .h files
If:
  PathMatch: .*\.h
CompileFlags:
  Add: [
    -xc-header,
    -std=gnu2x,            # c standard  c2x
    --include=Global.h,
  ]
Compiler: clang  # gcc
---
# Flags for .cpp files
If:
  PathMatch: .*\.(cc|cpp|c++)
CompileFlags:
  Add: [
    -xc++,
    -std=gnu++2b,            # c++ standard  c++2b
  ]
Compiler: clang++
ClangTidy:
  Add: modernize-*
# Remove: modernize-use-trailing-return-type
---
# Flags for .hpp files
If:
  PathMatch: .*\.(hh|hpp|h++)
CompileFlags:
  Add: [
    -xc++,
    -std=gnu++2b,            # c++ standard  c++2b
    --include=Global.h,
  ]
Compiler: clang++
ClangTidy:
  Add: modernize-*
