Completion:
  AllScopes: true

InlayHints:
  Enabled: true
  Designators: true
  ParameterNames: true
  DeducedTypes: true

Hover:
  ShowAKA: true

Diagnostics:
  UnusedIncludes: Strict
  # Suppress: [-Wunused-result, -Wunused, -Wunused-variable]
  # https://clang.llvm.org/extra/clang-tidy/checks/list.html
  ClangTidy:
    Add: [
      bugprone-*
      performance-*,
      portability-*,
      readability-*,
      google-*,
      misc-*,
      modernize-*,
    ]
    Remove: [
      bugprone-assignment-in-if-condition,
      bugprone-easily-swappable-parameters,

      # bugprone-branch-clone,
      # bugprone-implicit-widening-of-multiplication-result,
      # bugprone-macro-parentheses,
      # bugprone-narrowing-conversions,
      # bugprone-not-null-terminated-result,
      # bugprone-reserved-identifier,
      # bugprone-sizeof-expression,
      # bugprone-suspicious-include,
      # bugprone-suspicious-memory-comparison,
      # bugprone-unused-return-value,

      google-readability-braces-around-statements,
      google-readability-function-size,
      google-readability-todo,

      # misc-misplaced-const,
      # misc-no-recursion,
      # misc-unused-parameters,

      # modernize-macro-to-enum,

      # performance-no-int-to-ptr,

      readability-implicit-bool-conversion,
      readability-identifier-length,
      readability-magic-numbers,
      readability-braces-around-statements,
      readability-function-size,
      readability-function-cognitive-complexity,
      readability-isolate-declaration,
      readability-avoid-const-params-in-decls,

      # readability-else-after-return,
      # readability-misleading-indentation,
      # readability-redundant-declaration,
      # readability-redundant-function-ptr-dereference,
      # readability-suspicious-call-argument,
    ]

Index:
  StandardLibrary: Yes

# -g          = add debugging
# -l          = link shared library
# -L          = link external library
# -E          = preprocessor output only (out.i)
# -S          = assembly output          (out.s)
# -save-temps = get object file, preproc, assembly

# -fPIC          = position independent code
# -fverbose-asm  = if compiling with '-S' examine assemble output
# -fasm          = recognize asm keyword

# -finstrument-functions = adds code to call user supplied profiling functions

# -Werror  = turn warning to errors

# --coverage = gcov
# -fsanitize={address,thread,undefined}

CompileFlags:
  Add: [
      -Wall,   # all warnings
      -Wextra, # extra warnings
      -Wpedantic,

      -Wfloat-equal,   # testing floats for equality
      -Wundef,         # unitialized identifier evaluated in an #if
      -Wshadow,        # variable shadows another
      -Wpointer-arith, # anything dpends upon size of func or void
      -Wcast-align,    # pointer is cast such that required alignment of target is increased
      -Wcast-qual,     # pointer is cast to remove a type qualifier from target type
      -Wbad-function-cast,
      -Wold-style-definition,
      -Wredundant-decls,
      -Wstrict-aliasing=2,
      -Wstrict-prototypes, # func declared/defined without specifying variables
      -Wstrict-overflow=5,
      -Wwrite-strings,    # string constants 'const'
      -Waggregate-return, # funcs that return structs/unions are defined
      -Wswitch-default,   # switch statement does not have default
      -Wswitch-enum,      # switch statement has index of enum type last a case for an enumeration
      -Wconversion,       # implicit conversions that may alter value
      -Wsign-conversion,
      -Wunreachable-code, # self explanatory
      -Wnested-externs,
      -Wdisabled-optimization,
      -Winline,
      -Wformat,
      -Wformat-signedness,
      -Winit-self,
      # -Wpadded,

      -Wuninitialized,
      -Wlogical-op,
      -Wmissing-prototypes,
      -Wmissing-declarations,
      -Wvla,      # variable length arrays
      -Waddress,  # suspicious use of memory address

      -Wbool-compare,     # warn when comparing bool to integer
      -Wbool-operation,   # warn about certain boolean ops

      # -fsanitize=address,
      # -fsanitize=undefined,
      # -save-temps, # leave behind results of preprocess and assembly

      # OPTIMIZE
      # -fconserve-stack,  # don't optimize in a way that increases stack
      # -fstack-usage,     # output stack usage on a per function basis

      # SAFE
      # -fno-strict-aliasing,
      # -fno-delete-null-pointer-checks,
      # -fwrapv,           # assume signed arithmetic overflow wraps

      # Disable
      -Wno-unused,
      -Wno-unused-result,
      -Wno-unused-variable,
      -Wno-unused-function,
      # -Wno-format,

      # GNU
      # -fnested-functions,  # allow nested functions
      # -fblocks,            # enable blocks language feature
      -Wno-variadic-macros,  # don't warn about variadic macros
      -Wno-gnu-empty-struct, # don't warn about empty struct
      -Wno-gnu-binary-literal,

      # Use of non-standard escape character '\e' [clang -Wpedantic]
    ]
  Remove: []
  # Remove: -W*
---
# Flags for .c files
If:
  PathMatch: .*\.c
CompileFlags:
  Add: [
      -xc,
      # -std=gnu18, # c standard  c2x
      -std=gnu2x,            # c standard  c2x
    ]
  # Compiler: clang
  Compiler: gcc
---
# Flags for .h files
If:
  PathMatch: .*\.h
CompileFlags:
  Add: [
      -xc-header,
      -std=gnu2x, # c standard  c2x
      --include=Global.h,
    ]
  # Compiler: clang
  Compiler: gcc
---
# Flags for .cpp files
If:
  PathMatch: .*\.(cc|cpp|c\+\+)
CompileFlags:
  Add: [
      -xc++,
      -std=gnu++2b, # c++ standard  c++2b
    ]
  Compiler: clang++
Diagnostics:
  ClangTidy:
    Add: modernize-*
# Remove: modernize-use-trailing-return-type
---
# Flags for .hpp files
If:
  PathMatch: .*\.(hh|hpp|h\+\+)
CompileFlags:
  Add: [
      -xc++,
      -std=gnu++2b, # c++ standard  c++2b
      --include=Global.h,
    ]
  Compiler: clang++
Diagnostics:
  ClangTidy:
    Add: modernize-*
