description = "Configuration database"

# Directories to index.
dirs = [
  "~/.config"
]

# skip = "Dirs"
ignore_symlinks = true
ignore_hidden = false
gitignore = true

# Colored output (optional '#' or '0x' prefix)
# color = "FF5813"
