#!/usr/bin/env python

"""
CPU usage indicator used for tmux status bar
"""

try:
    import psutil
except:  # noqa: E722
    print("N/A")
    exit()


class bcolors:
    OKAY = "#[fg=#A3B95A, bg=default]"
    WARNING = "#[fg=#F79A32, bg=default]"
    FAIL = "#[fg=#CC6666, bg=default]"


cpu_usage = psutil.cpu_percent(interval=1)

if cpu_usage >= 80:
    print(bcolors.FAIL + " %s" % cpu_usage + "%")
elif cpu_usage >= 60:
    print(bcolors.WARNING + " %s" % cpu_usage + "%")
elif cpu_usage >= 40:
    print(bcolors.WARNING + " %s" % cpu_usage + "%")
elif cpu_usage >= 20:
    print(bcolors.OKAY + " %s" % cpu_usage + "%")
else:
    print(bcolors.OKAY + " %s" % cpu_usage + "%")
