#!/usr/bin/env python

"""cpu usage indicator

used for tmux status bar
"""
try:
    import psutil
except:
    print("N/A")
    exit()


class bcolors:
    OKGREEN = "#[fg=#98c379, bg=default]"
    WARNING = "#[fg=#e5c07b, bg=default]"
    FAIL = "#[fg=#e06c75, bg=default]"


cpu_usage = psutil.cpu_percent(interval=1)

if cpu_usage >= 80:
    print(bcolors.FAIL + " %s" % cpu_usage + "%")
elif cpu_usage >= 60:
    print(bcolors.WARNING + " %s" % cpu_usage + "%")
elif cpu_usage >= 40:
    print(bcolors.WARNING + " %s" % cpu_usage + "%")
elif cpu_usage >= 20:
    print(bcolors.OKGREEN + " %s" % cpu_usage + "%")
else:
    print(bcolors.OKGREEN + " %s" % cpu_usage + "%")
