#!/usr/bin/env python

"""
Memory usage indicator used for tmux status bar
"""

try:
    import psutil
except:  # noqa: E722
    print("N/A")
    exit()


class bcolors:
    OKAY = "#[fg=#A3B95A, bg=default]"
    WARNING = "#[fg=#F79A32, bg=default]"
    FAIL = "#[fg=#CC6666, bg=default]"


mem_usage = psutil.virtual_memory()[2]

if mem_usage >= 80:
    print(bcolors.FAIL + "﬙ %s" % mem_usage + "%")
elif mem_usage >= 60:
    print(bcolors.WARNING + "﬙ %s" % mem_usage + "%")
elif mem_usage >= 40:
    print(bcolors.WARNING + "﬙ %s" % mem_usage + "%")
elif mem_usage >= 20:
    print(bcolors.OKAY + "﬙ %s" % mem_usage + "%")
else:
    print(bcolors.OKAY + "﬙ %s" % mem_usage + "%")
