
## where to store your encryption key, default is your system data directory
key_path = "~/.local/share/atuin/dbkey"

## where to store your auth session token, default is your system data directory
session_path = "~/.local/share/atuin/session-token"

## date format used, either "us" or "uk"
db_path = "~/.config/atuin/history.db"
dialect = "us"
auto_sync = true
sync_frequency = "5m"

## address of the sync server
# sync_address = "https://api.atuin.sh"

## possible values: prefix, fulltext, fuzzy
search_mode = "fuzzy"
