#!/usr/bin/env zsh

# Desc: List connected bluetooth devices

bluetoothctl devices \
  | ${commands[hck]:-cut} -f2 \
  | while read r; do bluetoothctl info $r; done \
  | rg -e "Device|Connected|Name"
