#!/usr/bin/env bash

# Desc: Colorize output of strace

string_length=$(($(tput cols) - 95))
return_col=$(($(tput cols) - 55))
/usr/bin/strace -t -f -C -s "$string_length" -y -a $return_col -o \
  >(source-highlight --failsafe --lang-def $HOME/mybin/linux/strace.lang -f esc --style-file=esc.style >&2) \
  "${@}"
