#!/usr/bin/env zsh

notify-send \
    -i /usr/share/icons/Gruvbox-Material-Dark/48x48/apps/screengrab.svg \
    -a Screenshot \
    -u normal \
    -t 3000 'Screenshot will be taken in 3 seconds'

location="$HOME/Pictures/screenshot/$(date '+%Y-%m-%d_%H-%M').png"

sleep 3
maim -q "$location"
notify-send -a Screenshot -i "$location" -u normal -t 3000 'Screenshot taken'
