#!/usr/bin/env bash

#for mon_id in $(bspc query -M); do
#         bspc rule -a '*:*' -o monitor="$mon_id"
#         urxvt -name cmatrixterm -e zsh -ic "timeout 178 cbonsai -S -M 20 -L 105 -b 2" & #unimatrix -fans 88 -l 'o' -t 178 &
 #        bspc subscribe node_add -c 1 > /dev/null
#done
#wait -n
#jobs -rp | xargs -r -n1 kill

#tmux new-session -d -s matrix timeout 178 pipes.sh -t 1 -r 8000 #cbonsai -i -M 15 -L 150 -b 2 -m "$(fortune -e tao wisdom science medicine)"
#unimatrix -fans 88 -l 'o' -t 178

alacritty \
    -o window.startup_mode=Fullscreen \
    --class cmatrixterm \
    -e bash \
    -c 'sleep 0.2; timeout 178 pipes-rs -k heavy -r .5'

#tmux attach -t matrix \; set status off & disown

#qtile cmd-obj -o window -f toggle_fullscreen
#wid=$(xdotool search --classname "cmatrixterm")
#xdotool windowmove $wid -3 -3
#xdotool windowsize $wid 100% 100%
#wmctrl -r matrix -b toggle,fullscreen
