#!/usr/bin/env zsh

# Desc: generates a function named $1 which:
#     - executes $(which $1) [with args]
#     - suppresses output lines which match $2
#
# E.g., adding: _supress echo "hello\|world" will generate this function:
#
#     echo() { $(which echo) "$@" 2>&1 | tr -d '\r' | grep -v "hello\|world"; }
#
# From now on, using echo will work normally except that lines with
# hello or world will not show at the output. To see the generated functions,
# replace eval with echo below the 'tr' filter makes sure no spurious empty lines
# pass from some commands

suppress() {
  emulate -L zsh
  eval \
    "${1}() {
      \$(which $1) \"\$@\" 2>&1 \
          | tr -d '\r' \
          | rg -v \"$2\"
      }"
}

# _supress gedit          "Gtk-WARNING\|connect to accessibility bus"
# _supress gnome-terminal "accessibility bus\|stop working with a future version"
# _supress firefox        "g_slice_set_config"
