#!/bin/sh

if pidof picom; then
    killall picom
    notify-send \
        -a Picom \
        -i /usr/share/icons/Gruvbox-Material-Dark/32x32/apps/picom.svg \
        -u normal \
        -t 3000 "Picom killed"
    #dunstify -u normal -r 609 -t 3000 "Picom killed"
else
    picom --experimental-backends &
    notify-send \
        -a Picom \
        -i /usr/share/icons/Gruvbox-Material-Dark/32x32/apps/picom.svg \
        -u normal \
        -t 3000 "Picom Started"
    #dunstify -u normal -r 609 -t 3000 "Picom Started"
fi

# vim: ft=sh:et:sw=4:ts=2:sts=-1:fdm=marker:fmr={{{,}}}:
