directory: ~/Music
library: ~/.config/beets/library.db

plugins: lastgenre edit fetchart ftintitle lyrics fuzzy export info duplicates

fetchart:
  sources: filesystem coverart itunes amazon albumart lastfm google

lastgenre:
  auto: yes

lyrics:
  auto: yes

export:
  json:
    formatting:
      ensure_ascii: false
      indent: 4
      separators: [",", ": "]
      sort_keys: true
  csv:
    formatting:
      delimiter: ","
