#!/usr/bin/env zsh

# @desc backup task folder

emulate -L zsh -o extendedglob -o noshortloops -o warncreateglobal
zmodload -Fa zsh/parameter p:commands

local file dest src

file="task-$(date +'%Y%m%d').tar.gz"
dest="$BACKUP_DIR/task"
src="$XDG_CONFIG_HOME/task"

command mkdir -p "$dest"
xcompress a -o "${dest}/${file}" "$src"
