#!/usr/bin/env zsh

# @desc: copy files with dragon

typeset -a files
files=( ${(@f)"$(dragon -t -x)"} )

for file in "${files[@]}" {
  path="${file#file://}"
  name="${path:t}"
  command cp "$path" "${PWD}/${name}"
}
