#!/usr/bin/env zsh

# Desc: download a file by dropping it into a window

emulate -L zsh
autoload -U colors

local url name answer
url=$(dragon -t -x)

[[ -n "$url" ]] && {
  while [[ -z "$name" || -e "$name" ]] {
    read -r name

    if [[ -e "$name" ]]; then
      print -Pr -- "%F{3}$name%f exists"
      read -rq "?$fg_bold[red]Overwrite?$reset_color [y/n]? " answer
      [[ $ans = y ]] && break
      print -Pr -- "%F{4}%BFilename%f%f: "
  }

  [[ -n "$name" ]] && \
    command curl -o "$name" "$url" || \
    exit 1
} || exit 1
