#!/bin/sh

# Desc: uses dragon to download files

# This toy example uses wget and the --target mode to act
# as a drag-and-drop download tool.

~/.local/bin/dragon --target | while read url
do
    wget "$url"
done

# vim:ft=sh:et:sw=0:ts=2:sts=2:
