#!/usr/bin/env bash

PATH=:$PATH:
PATH=${PATH//:$(dirname $0):/:}
PATH=${PATH#:}
PATH=${PATH%:}

export HOME="$HOME/.local/home"
PNAME="$(basename $0)"

command -v "$PNAME" && {
    exec "$PNAME" "$@"
} || {
    exec "$@"
}
