#!/usr/bin/env bash

# Desc: create a fake home (sauce, .env is better)

PATH=:$PATH:
PATH=${PATH//:$(dirname $0):/:}
PATH=${PATH#:}
PATH=${PATH%:}

export HOME="$HOME/.local/home"
PNAME="$(basename $0)"

command -v "$PNAME" && {
    exec "$PNAME" "$@"
} || {
    exec "$@"
}
