#! /usr/bin/env zsh

# match: # no-parse: explain here
typeset pattern='^\s*#\s*no-parse.*\s+'

# comment next lines
fastmod --accept-all "$pattern" '$0#' "$@"
shfmt -w -s "$@"
# revert commented lines
fastmod --accept-all "(${pattern})#" '$1' "$@"
