#!/usr/bin/env zsh

# @desc: interactively kill process with fzf
# | awk 'BEGIN{OFS="\t"}{print $1, $2, $NF}' \

px ${@:-} \
  | sed 1d \
  | choose -o "\t" 0 1 -1 \
  | fzf --height=70% \
  | awk '{print $1}' \
  | xargs -I{} kill -TERM "{}"

# vim:ft=zsh:
