#!/bin/sh

# Desc: preview font as image

if [ $# -lt 2 ]; then
  echo "Usage : $0 font.otf output.png"
  exit 1
fi


PREVIEW_TEXT="ABCDEFGHIJKLM\n"\
"NOPQRSTUVWXYZ\n"\
"abcdefghijklm\n"\
"nopqrstuvwxyz\n"\
"1234567890\n"\
"!@$\%(){}[]"


convert -size "532x365" xc:"#ffffff" \
  -gravity center \
  -pointsize 38 \
  -font "$1" \
  -fill "#000000" \
  -annotate +0+0 "$PREVIEW_TEXT" \
  -flatten "$2"
