#!/usr/bin/env zsh

function cleanup() {
  exec 3>&-; rm "$FIFO_UEBERZUG"
}

if [[ -n "$SSH_CLIENT" || -n "$SSH_TTY" ]] {
  lf "$@"
} else {
  [[ ! -d "${XDG_CACHE_HOME}/lf" ]] && command mkdir -p "${XDG_CACHE_HOME}/lf"
  export FIFO_UEBERZUG="${XDG_CACHE_HOME}/lf/ueberzug-$$"
  command mkfifo -m o+w "$FIFO_UEBERZUG"
  trap cleanup HUP INT QUIT TERM PWR EXIT
  ueberzug layer -s <"$FIFO_UEBERZUG" -p json &
  exec 3>"$FIFO_UEBERZUG"
  lf "$@" 3>&-
}
