#!/usr/bin/env python3

# Desc: helper for newsboat

import sqlite3
import os
import errno


def make_sure_path_exists(path):
    try:
        os.makedirs(path)
    except OSError as exception:
        if exception.errno != errno.EEXIST:
            raise


con = sqlite3.connect(f"{os.environ['HOME']}/.newsboat/cache.db")
cur = con.cursor()

make_sure_path_exists('./Youtube/')

for row in cur.execute('select url, author from rss_item WHERE "unread"=1 and "url" like "%youtube%";'):
    url, author = row
    folder = author.replace(" ", "_").lower()
    make_sure_path_exists(f'./Youtube/{folder}')
    os.system(f'youtube-dl --restrict-filenames -o "./Youtube/{folder}/%(title)s-%(id)s.%(ext)s" {url}')

cur.execute('update rss_item set "unread" = 0 WHERE "unread"=1 and "url" like "%youtube%";')
con.commit()
con.close()
