#!/usr/bin/env zsh

function nga() {
  emulate -L zsh -o extendedglob
  local url
  local -a match mend mbegin
  url="$(command git remote get-url origin)"
  if [[ $url = (#b)*@*.com:(*) ]]; then
    url=${url//*/$match[1]}
  else
    url=${url:t2}
  fi
  url=${url%.*}

  if [[ -n "$DISPLAY" ]]; then
    print -n "${url//\//-}" | xsel -b --trim
    dunstify "Author:" "$url"
  else
    print -n "${url//\//-}" | osc52send
  fi
}

nga "$@"

# vim: ft=zsh:et:sw=0:ts=2:sts=2:tw=100
