#!/usr/bin/env zsh

ngu() {
  # confu="$(\
  #   sed -n '/\[remote\s.*/{n;s/\t//g;s/url = //p}' \
  #   $(git rev-parse --show-toplevel)/.git/config \
  #   | head -n1
  # )"
  confu="$(git remote get-url origin)"

  print -n "$confu" | xsel -b --trim
  notify-send "Copied" "$confu"

  # print -P "%F{14}%b$confu%f%b"
}

ngu
