#!/usr/bin/env zsh

function ngu() {
  # confu="$(\
  #   sed -n '/\[remote\s.*/{n;s/\t//g;s/url = //p}' \
  #   $(git rev-parse --show-toplevel)/.git/config \
  #   | head -n1
  # )"

  local confu
  confu="$(git remote get-url origin)"

  if [[ -n "$DISPLAY" ]]; then
    print -n "$confu" | xsel -b --trim
    dunstify "Copied" "$confu"
  else
    print -n "$confu" | osc52send
  fi

  # print -P "%F{14}%b$confu%f%b"
}

ngu
