#!/usr/bin/env zsh

# Desc: fzf tmux fifo with neovim

emulate -L zsh
local fifo args

fifo=/tmp/nvim-tmux-exit
mkfifo -m o+w $fifo || return 1

trap "command rm -f $fifo" EXIT SIGINT SIGTERM

(( $# == 0 )) && args="" || args="${(z)@}"

tmux split-window -bf zsh -c "nvim $args; echo $? > $fifo" || return 1
exit <$fifo

# This needs fixed
# exec {fd}<$fifo
# exec {NVIM_FIFO}>&-
