#!/usr/bin/env bash

# Desc: autotype pass password

set -ue


if ! command -v xdotool &> /dev/null; then
    printf "You need to install xdotool.\n" 1>&2
    exit 1
fi

output="$(pass $@)"

exit_code="$?"
if [[ "$exit_code" -gt 0 ]]; then
    exit "$exit_code"
fi

password="$(printf "%s" "$output" | head -n 1)"
username="$(printf "%s" "$output" | grep '^username: ' | cut -c 11-)"

active_window_id="$(xdotool getactivewindow)"

if [[ -n "$password" ]]; then
    if [[ -n "$username" ]]; then
        xdotool type --window "$active_window_id" "$username"
        xdotool key --window "$active_window_id" "Tab"
        xdotool type --window "$active_window_id" "i"
    fi

    xdotool type --window "$active_window_id" "$password"
fi
