#!/bin/sh
# Simple script to show the cpu temp formatted to be shown in polybar

temp=$(sensors | grep "Composite" | sed "s/Composite: *+//;s/°C .*//")
if [ 1 -eq "$(echo "$temp > 80" | bc)" ]; then
    printf "%%{F#dc3958}"
elif [ 1 -eq "$(echo "$temp > 60" | bc)" ]; then
    printf "%%{F#f79a32}";
fi

echo "$temp"°C
