#!/bin/sh

# Desc: general rclone copier

/usr/bin/rclone copy \
  --update \
  --verbose \
  --delete-after \
  --exclude ".DS_Store" \
  --exclude .git/ \
  --copy-links \
  --transfers 4 \
  --checkers 8 \
  --contimeout 60s \
  --timeout 300s \
  --retries 3 \
  --low-level-retries 10 \
  --stats 1s \
  --progress \
  "$1" "google-drive:${2}/"
