#!/bin/sh

# https://superuser.com/questions/1610715/how-can-i-use-caps-as-a-function-key-to-activate-arbitrary-combinations-on-oth
# https://unix.stackexchange.com/questions/414926/bind-capshjkl-to-arrow-keys-caps-to-esc

setxkbmap -layout us
xset r rate 300 50

# Method 1
# Sets caps lock to a hyper key when held down
# Sets caps lock to escape when pressed alone
# Sets caps lock to caps lock when pressed with shift

# setxkbmap -option caps:escape
mod="Hyper_L"

xmodmap -e "clear lock"
xmodmap -e "clear control"
xmodmap -e "clear mod3"
xmodmap -e "clear mod4"

# xmodmap -e "keycode 66 = Mode_switch"
# xmodmap -e "keycode 66 = Escape Caps_Lock"

xmodmap -e "keycode 66 = $mod Caps_Lock"

# xmodmap -e "keysym Caps_Lock = Hyper_L"
# xmodmap -e "add lock = Caps_Lock"

# If not clearing mod4
# xmodmap -e "remove mod4 = $mod"

xmodmap -e "add mod3 = Caps_Lock"
xmodmap -e "add control = Control_L Control_R"
xmodmap -e "add mod4 = Super_L Super_R"

xmodmap -e "keycode any = Escape"

# xcape -e "ISO_Level3_Shift=Escape"
# xcape -e "$mod=Escape"
killall xcape 2>/dev/null ; xcape -e "$mod=Escape"

# Turn off the caps lock if on since there is no longer a key for it.
# xset -q | grep "Caps Lock:\s*on" && xdotool key Caps_Lock


# ================
# xmodmap -e "keycode 66 = Mode_switch"
# xmodmap -e "h = h H Left"
# xmodmap -e "l = l L Right"
# xmodmap -e "k = k K Up"
# xmodmap -e "j = j J Down"

# xmodmap -e "u = u U Prior"
# xmodmap -e "i = i I Home"
# xmodmap -e "o = o O End"
# xmodmap -e "p = p P Next"

# xcape -e "Mod_switch=Escape"
