#!/bin/sh

# Sets caps lock to a hyper key when held down
# Sets caps lock to escape when pressed alone
# Sets caps lock to caps lock when pressed with shift

# https://superuser.com/questions/1610715/how-can-i-use-caps-as-a-function-key-to-activate-arbitrary-combinations-on-oth
# https://unix.stackexchange.com/questions/414926/bind-capshjkl-to-arrow-keys-caps-to-esc

# .xserverrc
# exec /usr/bin/X -ardelay 300 -arinterval 50 -nolisten tcp "$@"

xset r rate 300 50
setxkbmap -layout us
setxkbmap -option shift:both_capslock

# xmodmap -e "keysym Shift_R = Shift_R Caps_Lock Shift_R"
# xmodmap -e "keysym Shift_L = Shift_L Caps_Lock Shift_L"

# setxkbmap -option caps:escape
mod="Hyper_L"

xmodmap -e "clear lock"
xmodmap -e "clear control"
xmodmap -e "clear mod3"
xmodmap -e "clear mod4"

# xmodmap -e "keycode 66 = Mode_switch"
# xmodmap -e "keycode 66 = Escape Caps_Lock"

xmodmap -e "keycode 66 = $mod Caps_Lock"

# xmodmap -e "keysym Caps_Lock = Hyper_L"
# xmodmap -e "add lock = Caps_Lock"

# If not clearing mod4
# xmodmap -e "remove mod4 = $mod"

# xmodmap -e "add mod3 = Caps_Lock"
xmodmap -e "add mod3 = Hyper_L"
xmodmap -e "add control = Control_L Control_R"
xmodmap -e "add mod4 = Super_L Super_R"

xmodmap -e "keycode any = Escape"

# xcape -e "ISO_Level3_Shift=Escape"
# xcape -e "$mod=Escape"
killall xcape 2>/dev/null ; xcape -e "$mod=Escape"

# setxkbmap -option caps:hyper

# ================
# xmodmap -e "keycode 66 = Mode_switch"
# xmodmap -e "h = h H Left"
# xmodmap -e "l = l L Right"
# xmodmap -e "k = k K Up"
# xmodmap -e "j = j J Down"

# xmodmap -e "u = u U Prior"
# xmodmap -e "i = i I Home"
# xmodmap -e "o = o O End"
# xmodmap -e "p = p P Next"

# xcape -e "Mod_switch=Escape"
