#!/bin/bash

# Desc: ripgrep preview matches with fzf

rga-fzf() {
  RG_PREFIX="rga --files-with-matches"
  local file
  file="$(
    FZF_DEFAULT_COMMAND="$RG_PREFIX '$1'" \
      fzf --sort --preview="[[ ! -z {} ]] && rga --pretty --context 5 {q} {}" \
        --phony -q "$1" \
        --bind "change:reload:$RG_PREFIX {q}" \
        --preview-window="70%:wrap,nohidden"
  )" &&
  echo "opening $file" &&
  $EDITOR "$file"
}

rga-fzf
