#!/bin/sh

# dec: fzf wrapper for uni
# https://github.com/arp242/uni

# Usage:
#
#   dmenu-uni all            All codepoints, won't include ZWJ emoji sequences.
#   dmenu-uni emoji          All emojis.
#   dmenu-uni emoji-common   Common emojis

dmenu="fzf" # Use fzf instead

# Command to copy to clipboard:
# copy="xclip -rmlastnl -selection clipboard"
copy='xsel -b'

# Common emojis I use >99% of the time:
common="-or g:smileys g:hand-fingers-open g:hand-fingers-partial g:hand-single-finger g:hand-fingers-closed g:hands g:body-parts g:person-gesture"

# Display onlt the male variants:
#common="$common -gender male"

# Set skin tone:
#common="$common -tone mediumdark"

case "${1:-all}" in
all) uni -q p all | $dmenu | grep -o "^'.'" | tr -d "'" | $copy ;;
emoji) uni -q e all | $dmenu | cut -d ' ' -f1 | $copy ;;
emoji-common) uni -q e $common | $dmenu | cut -d ' ' -f1 | $copy ;;
*) uni -q e $@ | $dmenu | cut -d ' ' -f1 | $copy ;;
  #*)             echo >&2 "dmenu-uni: unknown '$1'" ;;
esac
