#!/usr/bin/env zsh

# Desc: upload to Firefox Send

emulate -L zsh
zmodload -Fa zsh/parameter p:commands

[[ -n "$1" && -s "$1" ]] && {
    if (( $+commands[ffsend] )) {
        ffsend -fiq u "$1";
    } elif [[ ${${(s:/:)"$(mimetype --output-format %m zman)"}[1]} = "text" ]] {
        curl -F "f:1=@$1" ix.io;
    } else {
        curl -s -F "file=@$1" https://file.io/?expires=1w | jq '.link' | tr -d '"'
    }
} || {
    builtin print -Pr -- "%F{1}%B[ERROR]%b%f: Not a text file"
}
