#!/bin/sh

# Desc: make a local archive of an entire website

# --mirror \
# -A png,jpg

wget \
  --recursive \
  --level inf \
  --timestamping \
  --no-remove-listing \
  --convert-links \
  --no-clobber \
  --page-requisites \
  --adjust-extension \
  --no-check-certificate \
  -e robots=off \
  --no-parent \
  --wait=3 \
  -U "Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)" \
  "$@"
