#!/usr/bin/env zsh

# Desc: open script in editor

setopt extendedglob
local Z fullp

# ${${(M)${(j: :)$(whence -va pw)}:#*function*}:+${$(whence -va pw)[-1]}}

Z="${ZDOTDIR}/functions/${argv}"
fullp=$(which "$argv")

if { file -b -L --mime-type "${fullp}" | grep -q "text/" }; then
  $EDITOR "$fullp"
elif [[ -f "$Z" ]]; then
  $EDITOR "$Z"
elif [[ -n ${${(M)${(j: :)$(whence -vw "$argv")}:#*function*}} ]]; then
  "$EDITOR" ${$(whence -va "$argv")[-1]}
else
  print -Pr -- "%F{1}$argv%f (%F{14}$fullp%f) is not a text file"
fi
