#!/usr/bin/env zsh

# Desc: open script in editor with fzf

zmodload -Fa zsh/parameter p:commands
setopt extendedglob
local fdir fullp

fdir="${ZDOTDIR}/functions/${argv}"
fullp="$(print -rl -- "$commands[@]" | lscolors | fzf +m)"

[[ -n "$fullp" ]] && {
  if { file -b -L --mime-type "${fullp}" | grep -q "text/" }; then
    $EDITOR "$fullp"
  elif [[ -f "$fdir" ]]; then
    $EDITOR "$fdir"
  else
    print -Pr -- "%F{14}$fullp%f is not a text file"
  fi
}
