#!/usr/bin/env bash

bspc rule -r "*"

pgrep -x sxhkd     >/dev/null || sxhkd &
pgrep -x pueued    >/dev/null && pueue clean
pgrep -x rss-watch >/dev/null || run-rss-watch

xsetroot -cursor_name left_ptr &

remaps &
# remaps-mode_shift &

# thunar --daemon &
# spacefm -d &
pgrep -x pcmanfm >/dev/null || pcmanfm -d &
pgrep -x autokey-gtk >/dev/null || autokey-gtk &>/dev/null &
launchpolybar &

bspc monitor -d I II III IV V

bspc config automatic_scheme alternate
bspc config initial_polarity second_child

bspc config split_ratio          0.50

bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config click_to_focus       true

bspc config single_monocle       true
bspc config gapless_monocle      false
bspc config borderless_monocle   false

bspc config border_width          5
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#a98698"
bspc config presel_feedback_color "#4C96A8"
bspc config urgent_border_color   "#dd2727"

# bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
# bspc config remove_disabled_monitors    true
# bspc config remove_unplugged_monitors   true
# bspc config merge_overlapping_monitors  true

bspc config pointer_modifier control
bspc config pointer_action1 resize_side
bspc config pointer_action2 move
bspc config pointer_action3 resize_corner

# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)

bspc rule -a Firefox desktop='^2'
bspc rule -a Screenkey manage=off
# bspc rule -a Screenkey --unmanage
# bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Sxiv state=floating follow=on
bspc rule -a "feh" state=floating
bspc rule -a "Ulauncher" border=off follow=on
bspc rule -a "System Settings"  state=floating follow=on
bspc rule -a Pinentry state=floating center=on

bspc rule -a Alacritty:cmatrixterm state=fullscreen
bspc rule -a Alacritty:dropdown state=floating

# bspc rule -a lattedock layer=below manage=off border=off
#bspc rule -a lattedock manage=off

# bspc rule -a Gimp desktop='^8' state=floating follow=on
