#! /bin/sh

bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &
xsetroot -cursor_name left_ptr &

# /home/lucas/mybin/remaps &
# remaps &
# sxhkd &

remaps &
thunar --daemon &
launchpolybar &

# pgrep -x nm-applet > /dev/null || nm-applet &
# pgrep -x blueman-applet >/dev/null || blueman-applet &
# pgrep -x udiskie >/dev/null || udiskie & # --tray
# clipit &

# xrdb ~/.Xresources &
# pgrep -x picom >/dev/null || picom -b --experimental-backends &
# pgrep -x hsetroot >/dev/null || hsetroot -cover ~/Pictures/wallpapers/0012.jpg &
# pgrep -x flameshot >/dev/null || flameshot &
# pgrep -x fcitx >/dev/null || fcitx -d &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d I II III IV V

# bspc config automatic_scheme alternate
bspc config initial_polarity second_child

bspc config split_ratio          0.50

bspc config window_gap           10
bspc config top_padding          30
bspc config bottom_padding       0
bspc config left_padding         0
bspc config right_padding        0
bspc config click_to_focus       true

bspc config single_monocle       true
bspc config gapless_monocle      false
bspc config borderless_monocle   true

bspc config border_width          5
bspc config normal_border_color   "#4c566a"
bspc config active_border_color   "#1e1e1e"
bspc config focused_border_color  "#EF1D55"
bspc config presel_feedback_color "#4C96A8"
bspc config urgent_border_color   "#dd2727"

# bspc config focus_by_distance           true
bspc config focus_follows_pointer       true
# bspc config remove_disabled_monitors    true
# bspc config remove_unplugged_monitors   true
# bspc config merge_overlapping_monitors  true
#
# bspc config pointer_modifier  mod4
# bspc config pointer_action1   move
# bspc config pointer_action2   resize_side
# bspc config pointer_action3   resize_corner

bspc config pointer_modifier control
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

# xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DisplayPort-0)

bspc rule -a Firefox desktop='^2'
bspc rule -a Screenkey manage=off
bspc rule -a mpv state=fullscreen
bspc rule -a Zathura state=tiled
bspc rule -a Sxiv state=floating follow=on
bspc rule -a "System Settings"  state=floating follow=on

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
