[scripts.all-services]
command = 'systemctl list-unit-files --type=service'
description = 'list all services'
tags = ['systemctl']

[scripts.dmesg-sudo]
command = 'sudo sysctl -w kernel.dmesg_restrict=0'
description = 'enable no sudo for dmesg'
tags = ['']

[scripts.ec]
command = '$EDITOR /home/lucas/.config/pier/config.toml'
description = 'edit configuration file'

[scripts.enabled-services]
command = 'systemctl list-unit-files --state=enabled'
description = 'list enabled services'
tags = ['systemctl']

[scripts.ex-mod-conf]
command = '''expac -S -H M '%k\t%n' $(pacman -Qqu) | sort -sh'''
description = 'expac - list modified files'
tags = [
    'pman',
    'expac',
]

[scripts.ex-recent]
command = '''expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n 20 | tac'''
description = 'expac - recently installed (20)'
tags = [
    'pman',
    'epxac',
]

[scripts.ex-regex]
command = "expac -Ss '%-30n %-8v %d'"
description = 'expac - search regex'
tags = [
    'pman',
    'epxac',
]

[scripts.ex-sall]
command = '''pacman -Slq | fzf --preview 'pacman -Si {}' --layout=reverse'''
description = 'expac - search all (fzf)'
tags = [
    'pman',
    'epxac',
]

[scripts.ex-sinstalled]
command = '''
  pacman -Qq | fzf --preview 'pacman -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | less)'
'''
description = 'expac - search installed (fzf)'
tags = ['pman']

[scripts.ex-upgrade]
command = '''expac -S -H M '%k\t%n' $(pacman -Qqu) | sort -sh'''
description = 'expac - upgrade & download size'
tags = [
    'pman',
    'epxac',
]

[scripts.testing]
command = '''
notify-send 'testing' '$@'
'''
description = 'testing'

[scripts.tomb-create]
command = '''
#!/usr/bin/env zsh

name="${2:-secret}"

tomb dig -s "${1:-100}" "${name}.tomb" -f
print -P "%F{1}Created%f: %F{2}${name}.tomb%f"

tomb forge "${name}.tomb.key" -gr E93ACCAAAEB024788C106EDEC011CBEF6628B679 -f
print -P "%F{1}Created%f: %F{2}${name}.tomb.key%f"

tomb lock "${name}.tomb" -k "${name}.tomb.key" -f
print -P "%F{1}Locked%f: %F{2}${name}.tomb%f"

tomb open "${name}.tomb" -k "${name}.tomb.key" -f
print -P "%F{1}Opened%f: %F{2}${name}.tomb%f"
'''
description = 'create a tomb'
tags = [
    'tomb',
    'encrypt',
]

[default]
