#!/bin/sh
# AUTHOR: lmburns
#
# DATE: 2023-04-12 17:26
#
# DESC: Elvi to search 4plebs (4chan archives)
# elvis: 4plebs		-- Search 4plebs (archive.4plebs.org)
. surfraw || exit 1

w3_usage_hook() {
  cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search 4plebs (archive.4plebs.org)
EOF
  w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
  w3_browse_url "https://archive.4plebs.org"
  exit
fi

set -f
escaped_args="$(w3_url_of_arg $w3_args)"
it="$escaped_args"
search_url="https://archive.4plebs.org/pol/search/text/"
search_url="$search_url$escaped_args"
w3_browse_url "$search_url"
