#!/bin/sh
# AUTHOR: lmburns
#
# DATE: 2023-04-12 17:26
#
# DESC: Elvi to search bitchute videos
# elvis: bitchute	-- Search bitchute (bitchute.com)
. surfraw || exit 1

w3_usage_hook () {
  cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search bitchute (bitchute.com)
EOF
  w3_global_usage
}


w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
  w3_browse_url "https://bitchute.com"
  exit
fi

set -f
escaped_args="$(w3_url_of_arg $w3_args)"
it="$escaped_args"
search_url="https://bitchute.com/search/?query="
search_url="$search_url$escaped_args"
w3_browse_url "$search_url"
