#!/bin/sh
# AUTHOR: lmburns
#
# DATE: 2023-04-13
#
# DESC: Elvi to search dictionary (dictionary.com)
# elvis: dictionary	-- Search dictionary for definitions (dictionary.com)
. surfraw || exit 1

w3_usage_hook () {
  cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search dictionary for definitions (dictionary.com)
EOF
  w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
  w3_browse_url "https://dictionary.com"
  exit
fi

set -f
escaped_args="$(w3_url_of_arg $w3_args)"
it="$escaped_args"
search_url="https://dictionary.com/browse/"
search_url="$search_url$escaped_args"
w3_browse_url "$search_url"
