#!/bin/sh
# AUTHOR: lmburns
#
# DATE: 2023-04-13 11:57
#
# DESC: Elvi to search for macOS applications (mactorrents.io)
# elvis: mactorrent	-- Search for macOS applications (mactorrents.io)
. surfraw || exit 1

w3_usage_hook () {
  cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search mactorrents (mactorrents.io)
EOF
  w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
  w3_browse_url "https://mactorrents.io"
  exit
fi

set -f
escaped_args="$(w3_url_of_arg $w3_args)"
it="$escaped_args"
search_url="https://mactorrents.io/?s="
search_url="$search_url$escaped_args"
w3_browse_url "$search_url"
