#!/bin/sh
# AUTHOR: Lucas Burns
#
# DATE: 2021-06-06
#
# DESC: Elvi to search manned
# elvis: manned          -- Search Manned Manpage (www.manned.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search manned (www.manned.org) for man pages
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://www.manned.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://manned.org/browse/search?q=${escaped_args}"
fi
