#!/bin/sh
# AUTHOR: lmburns
#
# DATE: 2023-04-13 11:53
#
# DESC: Elvi to search perldocs (perldoc.perl.org)
# elvis: perldoc		-- Search perldoc (perldoc.perl.org)
. surfraw || exit 1

w3_usage_hook ()
{
  cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search perldoc (perldoc.perl.org)
EOF
  w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
  w3_browse_url "https://perldoc.perl.org"
  exit
fi

set -f
escaped_args="$(w3_url_of_arg $w3_args)"
it="$escaped_args"
search_url="https://perldoc.perl.org/search?q="
search_url="$search_url$escaped_args"
w3_browse_url "$search_url"
