#!/bin/sh
# AUTHOR: lmburns
#
# DATE: 04-20-2023
#
# DESC: Elvi to search pgpmit for PGP keys (pgp.mit.edu)
# elvis: pgpmit	-- Search pgpmit for PGP keys (pgp.mit.edu)
. surfraw || exit 1

w3_usage_hook () {
  cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search pgpmit (pgp.mit.edu)
EOF
  w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
  w3_browse_url "https://pgp.mit.edu"
  exit
fi

set -f
escaped_args="$(w3_url_of_arg $w3_args)"
it="$escaped_args"
search_url="https://pgp.mit.edu/pks/lookup?search="
search_url="${search_url}${escaped_args}&op=index"
w3_browse_url "$search_url"
