#!/bin/sh
#
# AUTHOR: Lucas Burns
#
# DATE: 2021-06-06
#
# DESC: Elvi to search R Language Documentation
# elvis: rdoc            -- Search RDocumentation (www.rdocumentation.org)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search manned (www.rdocumentation.org) for man pages
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
if test -z "$w3_args"; then
    w3_browse_url "https://rdocumentation.org/"
else
    escaped_args=`w3_url_of_arg $w3_args`
    w3_browse_url "https://www.rdocumentation.org/search?q=${escaped_args}"
fi
