#!/bin/sh
# AUTHOR: lmburns
#
# DATE: 2023-04-13
#
# DESC: Elvi to search wikitionary (en.wikitionary.org)
# elvis: wikitionary	-- Search wikitionary for definitions (en.wikitionary.org)
. surfraw || exit 1

w3_usage_hook () {
  cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search wikitionary (en.wikitionary.org)
EOF
  w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
  w3_browse_url "https://en.wikitionary.org"
  exit
fi

set -f
escaped_args="$(w3_url_of_arg $w3_args)"
it="$escaped_args"
search_url="https://en.wiktionary.org/w/index.php?fulltext=Search&search="
search_url="$search_url${escaped_args}&title=Special%3ASearch"
w3_browse_url "$search_url"
