#!/bin/sh
# AUTHOR: lmburns
#
# DATE: 2023-04-13 11:53
#
# DESC: Elvi to search wikispooks (wikispooks.com)
# elvis: wikispooks	-- Search wikispooks (wikispooks.com)
. surfraw || exit 1

w3_usage_hook () {
  cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search wikispooks (wikispooks.com)
EOF
  w3_global_usage
}

w3_config
w3_parse_args "$@"

if test -z "$w3_args"; then
  w3_browse_url "https://wikispooks.com"
  exit
fi

set -f
escaped_args="$(w3_url_of_arg $w3_args)"
it="$escaped_args"
search_url="https://wikispooks.com/w/index.php?search="
search_url="$search_url${escaped_args}&title=Special%3ASearch&fulltext=Search"
w3_browse_url "$search_url"
