# [[snippets]]
# description = ""
# command = ""
# tag = [""]
# output = ""

##########
## RUST ##
##########
[[snippets]]
description = "run cp"
command = "cargo run -- cp app.rs opt.rs"
tag = ["rust"]
output = ""

[[snippets]]
description = "run clear"
command = "cargo run -- clear opt.rs"
tag = ["rust"]
output = ""

#########
## GIT ##
#########
# Replace commit reference: git tag -fa <tagname>
[[snippets]]
description = "git remove tag"
command = "git push origin :refs/tags/"
output = ""
tag = ["git"]


#########
#########
[[snippets]]
description = "cpu/memory"
command = """
  ps -A -o %cpu,%mem \
    | awk '{ cpu += $1; mem += $2} END {print \"CPU: \"  cpu,\"MEM: \"  mem}'
"""
output = ""
tag = ["system"]

[[snippets]]
description = "refresh wifi"
command = "ip link set wlp58s0 down && sleep 5 && ip link set wlp58s0 up"
output = ""
tag = ["system"]

[[snippets]]
description = "systemctl - enabled services"
command = "systemctl list-unit-files --state=enabled"
output = ""
tag = ["system"]

[[snippets]]
description = "systemctl - all services"
command = "systemctl list-unit-files --type=service"
output = ""
tag = ["system"]

[[snippets]]
description = "disable sudo for dmesg"
command = "sudo sysctl -w kernel.dmesg_restrict=0"
output = ""
tag = ["system"]

[[snippets]]
description = "expac - upgrade & download size"
command = "expac -S -H M '%k\t%n' $(pacman -Qqu) | sort -sh"
output = ""
tag = ["expac", "pacman"]

[[snippets]]
description = "expac - recently installed (20)"
command = "expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n 20 | tac"
output = ""
tag = ["expac", "pacman"]

[[snippets]]
description = "expac - search regex"
command = "expac -Ss '%-30n %-8v %d'"
output = ""
tag = ["expac", "pacman"]

[[snippets]]
description = "expac - list modified files"
command = "expac -S -H M '%k\t%n' $(paru -Qqu) | sort -sh"
output = ""
tag = ["expac", "pacman"]

[[snippets]]
description = "pacman - search installed (fzf)"
command = """
  paru -Qq \
    | fzf --preview 'paru --color=always -Qil {}' \
          --layout=reverse \
          --bind 'enter:execute(paru -Qil {} | bat)' \
          --preview-window=':nohidden'
"""
output = ""
tag = ["pacman"]

[[snippets]]
description = "pacman - search all (fzf)"
command = """
  paru -Slq \
    | fzf --preview 'paru --color=always -Si {}' \
          --layout=reverse \
          --preview-window=':nohidden'
"""
output = ""
tag = ["pacman"]

[[snippets]]
description = "pacman - installed regex"
command = "paru -Ssq "
output = ""
tag = ["pacman"]

[[snippets]]
description = "lsof - user"
command = "lsof -u lucas"
output = ""
tag = ["lsof"]

[[snippets]]
description = "lsof - user; exclude '^'"
command = "lsof -u lucas"
output = ""
tag = ["lsof"]

[[snippets]]
description = "set natural scrolling"
command = "xinput set-prop 23 315 1"
output = ""
tag = ["xinput"]
