[[snippets]]
description = "cpu/memory"
command = "ps -A -o %cpu,%mem | awk '{ cpu += $1; mem += $2} END {print \"CPU: \"  cpu,\"MEM: \"  mem}'"
output = ""

[[snippets]]
description = "refresh wifi"
command = "ip link set wlp58s0 down && sleep 5 && ip link set wlp58s0 up"
output = ""

[[snippets]]
description = "systemctl - enabled services"
command = "systemctl list-unit-files --state=enabled"
output = "echo 'hi'"

[[snippets]]
description = "systemctl - all services"
command = "systemctl list-unit-files --type=service"
output = ""

[[snippets]]
description = "disable sudo for dmesg"
command = "sudo sysctl -w kernel.dmesg_restrict=0"
output = ""

[[snippets]]
description = "expac - upgrade & download size"
command = "expac -S -H M '%k\t%n' $(pacman -Qqu) | sort -sh"
output = ""

[[snippets]]
description = "expac - recently installed (20)"
command = "expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n 20 | tac"
output = ""

[[snippets]]
description = "expac - search regex"
command = "expac -Ss '%-30n %-8v %d'"
output = ""

[[snippets]]
description = "expac - list modified files"
command = "expac -S -H M '%k\t%n' $(pacman -Qqu) | sort -sh"
output = ""

[[snippets]]
description = "pacman - search installed (fzf)"
command = "pacman -Qq | fzf --preview 'paru --color=always -Qil {}' --layout=reverse --bind 'enter:execute(pacman -Qil {} | bat)' --preview-window=':nohidden'"
output = ""

[[snippets]]
description = "pacman - search all (fzf)"
command = "pacman -Slq | fzf --preview 'paru --color=always -Si {}' --layout=reverse --preview-window=':nohidden'"
output = ""
