# [[snippets]]
# description = ""
# command = ""
# tag = [""]
# output = ""

# ╭──────────────────────────────────────────────────────────╮
# │                           Rust                           │
# ╰──────────────────────────────────────────────────────────╯
[[snippets]]
description = "run cp"
command = "cargo run -- cp app.rs opt.rs"
tag = ["rust"]
output = ""

[[snippets]]
description = "run clear"
command = "cargo run -- clear opt.rs"
tag = ["rust"]
output = ""

# ╭──────────────────────────────────────────────────────────╮
# │                           Git                            │
# ╰──────────────────────────────────────────────────────────╯
# Replace commit reference: git tag -fa <tagname>
[[snippets]]
description = "git remove tag"
command = "git push origin :refs/tags/"
tag = ["git"]
output = ""

# ╭──────────────────────────────────────────────────────────╮
# │                         Package                          │
# ╰──────────────────────────────────────────────────────────╯
# ╭───────╮
# │ Expac │
# ╰───────╯
[[snippets]]
description = "expac - recently installed (20)"
command = "expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n 20 | tac"
tag = ["expac", "pacman", "pacman:recent"]
output = ""

[[snippets]]
description = "expac - modified files"
command = "expac -S -H M '%k\t%n' $(paru -Qqu) | sort -sh"
tag = ["expac", "pacman", "pacman:modified"]
output = ""

[[snippets]]
description = "expac - upgrade & download size"
command = "expac -S -H M '%k\t%n' $(pacman -Qqu) | sort -sh"
tag = ["expac", "pacman", "pacman:size"]
output = ""

[[snippets]]
description = "expac - search packages by size"
command = "expac --timefmt='%Y-%m-%d %T' '%l\t%n' | sort | tail -n 20 | tac"
tag = ["expac", "pacman", "pacman:size"]
output = ""

[[snippets]]
description = "expac - search regex"
command = "expac -Ss '%-30n %-8v %d'"
tag = ["expac", "pacman", "pacman:regex"]
output = ""

# expac "%n %m" -l'\n' -Q $(pacman -Qq) | sort -rhk 2 | less

# ╭────────╮
# │ Pacman │
# ╰────────╯
[[snippets]]
description = "pacman - installed (fzf)"
command = """
  paru -Qq \
    | fzf --preview 'paru --color=always -Qil {}' \
          --layout=reverse \
          --bind 'enter:execute(paru -Qil {} | bat)' \
          --preview-window=':nohidden'
"""
tag = ["pacman", "pacman:installed", "pacman:fzf"]
output = ""

[[snippets]]
description = "pacman - unneeded (fzf)"
command = """
  paru -Qdtq \
    | fzf --preview 'paru --color=always -Qil {}' \
          --layout=reverse \
          --bind 'enter:execute(paru -Qil {} | bat)' \
          --bind '-:execute(paru -R {})' \
          --preview-window=':nohidden'
"""
tag = ["pacman", "pacman:unneeded", "pacman:fzf"]
output = ""

[[snippets]]
description = "pacman - all (fzf)"
command = """
  paru -Slq \
    | fzf --preview 'paru --color=always -Si {}' \
          --layout=reverse \
          --preview-window=':nohidden'
"""
tag = ["pacman", "pacman:all", "pacman:fzf"]
output = ""

[[snippets]]
description = "pacman - installed regex"
command = "paru -Ssq "
tag = ["pacman", "pacman:installed", "pacman:regex"]
output = ""

# ╭──────────────────────────────────────────────────────────╮
# │                          System                          │
# ╰──────────────────────────────────────────────────────────╯
[[snippets]]
description = "systemctl - enabled services"
command = "systemctl list-unit-files --state=enabled"
tag = ["sys", "systemd"]
output = ""

[[snippets]]
description = "systemctl - all services"
command = "systemctl list-unit-files --type=service"
tag = ["sys", "systemd"]
output = ""

[[snippets]]
description = "cpu/memory"
command = """
  ps -A -o %cpu,%mem \
    | awk '{ cpu += $1; mem += $2} END {print \"CPU: \"  cpu,\"MEM: \"  mem}'
"""
tag = ["sys", "stat", "process"]
output = ""

[[snippets]]
description = "refresh wifi"
command = "ip link set wlp58s0 down && sleep 5 && ip link set wlp58s0 up"
tag = ["sys", "wifi"]
output = ""

[[snippets]]
description = "disable sudo for dmesg"
command = "sudo sysctl -w kernel.dmesg_restrict=0"
tag = ["sys", "sysctl"]
output = ""

[[snippets]]
description = "lsof - user"
command = "lsof -u lucas"
tag = ["lsof", "sys"]
output = ""

[[snippets]]
description = "lsof - user; exclude '^'"
command = "lsof -u lucas"
tag = ["lsof", "sys"]
output = ""

#  ╭──────────────────────────────────────────────────────────╮
#  │                           X11                            │
#  ╰──────────────────────────────────────────────────────────╯
[[snippets]]
description = "set natural scrolling"
command = "xinput set-prop 23 315 1"
tag = ["xinput", "x11"]
output = ""
